// hardcoded sounds, defined in sounds.cfg
enum
{
	S_JUMP = 0,
	S_SOFTLAND, S_HARDLAND,
	S_BULLETAIR1, S_BULLETAIR2, S_BULLETHIT, S_BULLETWATERHIT,
	S_KNIFE, 
	S_PISTOL, S_RPISTOL,
	S_SHOTGUN, S_RSHOTGUN,
	S_BOLT, S_RBOLT,
	S_RPG, // no bow reload
	S_SUBGUN, S_RSUBGUN,
	S_SNIPER, S_RSNIPER,
	S_ASSAULT, S_RASSAULT,
	S_ASSAULT2, S_RASSAULT2,
	S_ITEMAMMO, S_ITEMHEALTH,
	S_ITEMARMOR, S_ITEMAKIMBO, 
	S_NOAMMO, S_AKIMBOOUT, 
	S_PAIN1, S_PAIN2, S_PAIN3, S_PAIN4, S_PAIN5, S_PAIN6,
	S_DIE1, S_DIE2, 
	S_FEXPLODE, 
	S_SPLASH1, S_SPLASH2,
	S_FLAGDROP, S_FLAGPICKUP, S_FLAGRETURN, S_FLAGSCORE,
	S_GRENADEPULL, S_GRENADETHROW, S_GRENADEBOUNCE1, S_GRENADEBOUNCE2, S_RAKIMBO,
	S_GUNCHANGE, 
	S_GIB,
	S_CALLVOTE, S_VOTEPASS, S_VOTEFAIL,
	S_FOOTSTEPS, S_FOOTSTEPSCROUCH, S_WATERFOOTSTEPS, S_WATERFOOTSTEPSCROUCH,
	S_CROUCH, S_UNCROUCH,
	S_MENUSELECT, S_MENUENTER,
	S_UNDERWATER,
	S_TINNITUS,
	S_V_HEADSHOT,
	S_V_FIRST,
	S_MAINEND = S_V_FIRST,

	S_V_AFFIRMATIVE,
	S_V_ALLRIGHTSIR,
	S_V_COMEONMOVE,
	S_V_COMINGINWITHTHEFLAG,
	S_V_COVERME,
	S_V_DEFENDTHEFLAG,
	S_V_ENEMYDOWN,
	S_V_GOGETEMBOYS,
	S_V_GOODJOBTEAM,
	S_V_IGOTONE,
	S_V_IMADECONTACT,
	S_V_IMATTACKING,
	S_V_IMONDEFENSE,
	S_V_IMONYOURTEAMMAN,
	S_V_NEGATIVE,
	S_V_NOCANDO,
	S_V_RECOVERTHEFLAG,
	S_V_SORRY,
	S_V_SPREADOUT,
	S_V_STAYHERE,
	S_V_STAYTOGETHER,
	S_V_THERESNOWAYSIR,
	S_V_WEDIDIT,
	S_V_YES,
	S_V_NICESHOT,
	S_VOICEEND = S_V_NICESHOT,
	S_NULL
};

// sound priorities
enum
{
	SP_LOW = 0,
	SP_NORMAL,
	SP_HIGH,
	SP_HIGHEST
};

enum 
{
	M_FLAGGRAB = 0,
	M_LASTMINUTE1,
	M_LASTMINUTE2
};

