name: Build

on:
  push:
    branches: [ main, github-actions_build ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  ver: ${{ github.ref_type == 'tag' && format('_{0}', github.ref_name) || '' }}
  is_release: ${{ github.ref_type == 'tag' }}
  compress_flags: ${{ github.ref_type == 'tag' && '-mx=9 -mfb=258 -mpass=15' || '-mx=5' }}

jobs:
  # notification:
  #   runs-on: ubuntu-latest
  #   name: Notifications
  #   steps:
  #   - name: IRC notification
  #     uses: Gottox/irc-message-action@v1
  #     with:
  #       channel: '#acreloaded-dev'
  #       nickname: ACRbot-GitHub
  #       message: |-
  #         ${{ github.repository }} <${{ github.event.commits[0].author.name }}> ${{ github.event.ref }}: ${{ github.event.before }} -> ${{ github.event.after }} ${{ github.event.commits[0].message }} ${{ github.event.compare }} (${{ github.run_id }} #${{ github.run_number }}) ${{ github.action_path }}
  #   if: github.event_name == 'push'

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Windows XP build tools
        run: |
          "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\setup.exe" modify --quiet --productId Microsoft.VisualStudio.Product.Enterprise --channelId VisualStudio.17.Release --add Microsoft.VisualStudio.Component.WinXP
        shell: cmd
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Compile Client
        run: msbuild .\source\vcpp\cube.sln /p:Configuration=Release
      - name: Compile Server
        run: msbuild .\source\vcpp\cube.sln /p:Configuration=Standalone
      - uses: actions/upload-artifact@v4
        with:
          name: bin_win
          path: bin_win32/acr_*.exe

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update
      - run: sudo apt-get install -y ${{ matrix.packages }} make automake libsdl1.2-dev libsdl-image1.2-dev libopenal-dev libvorbis-dev libcurl3-dev
      - working-directory: ./source/src
        run: make install
        env:
          CC: ${{ matrix.cc }}
          CC_FOR_BUILD: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
          CXX_FOR_BUILD: ${{ matrix.cxx }}
      - run: |
          mv bin_unix/native_client bin_unix/linux_64_client
          mv bin_unix/native_server bin_unix/linux_64_server
        if: matrix.official
      - uses: actions/upload-artifact@v4
        with:
          name: bin_linux
          path: bin_unix/*
        if: matrix.official
    continue-on-error: ${{ !matrix.official }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: gcc
            cc: gcc
            cxx: g++
            packages: gcc g++
            official: true
          - name: clang
            cc: clang
            cxx: clang++
            packages: clang

  package:
    runs-on: ubuntu-latest
    needs: [ build_windows, build_linux ]
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - run: sudo apt install p7zip-full
      - uses: actions/checkout@v4
        with:
          path: repo
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - run: |
          cp artifacts/bin_win/*.exe repo/bin_win32/
          mkdir -p repo/bin_unix
          cp artifacts/bin_linux/* repo/bin_unix/

      # Package
      - working-directory: ./repo/source
        run: ./package_acr.sh "$ver"
      - name: Compress
        working-directory: ./ACR_packaged
        run: |
          7za a ${{ env.compress_flags }} out/acr_${ver}-l.zip ./acr_${ver}-l/*
          7za a ${{ env.compress_flags }} out/acr_${ver}-w.zip ./acr_${ver}-w/*
          7za a ${{ env.compress_flags }} out/acr_${ver}-serv.zip ./acr_${ver}-serv/*
          7za a ${{ env.compress_flags }} out/acr_${ver}-src.zip ./acr_${ver}-src/*
          7za a ${{ env.compress_flags }} out/acr_${ver}-l_bin.zip ../repo/bin_unix/*
          7za a ${{ env.compress_flags }} out/acr_${ver}-w_bin.zip ../repo/bin_win32/acr_*.exe
          cd out
          sha256sum -b * > ../SHA256SUMS
          sha512sum -b * > ../SHA512SUMS

      # Upload artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: SHA256SUMS
          path: ACR_packaged/SHA256SUMS
      - uses: actions/upload-artifact@v4
        with:
          name: SHA512SUMS
          path: ACR_packaged/SHA512SUMS
      - uses: actions/upload-artifact@v4
        with:
          name: acr_${{ env.ver }}-l.zip
          path: ACR_packaged/out/acr_${{ env.ver }}-l.zip
          compression-level: 0
      - uses: actions/upload-artifact@v4
        with:
          name: acr_${{ env.ver }}-w.zip
          path: ACR_packaged/out/acr_${{ env.ver }}-w.zip
          compression-level: 0
      - uses: actions/upload-artifact@v4
        with:
          name: acr_${{ env.ver }}-serv.zip
          path: ACR_packaged/out/acr_${{ env.ver }}-serv.zip
          compression-level: 0
      - uses: actions/upload-artifact@v4
        with:
          name: acr_${{ env.ver }}-src.zip
          path: ACR_packaged/out/acr_${{ env.ver }}-src.zip
          compression-level: 0
      - uses: actions/upload-artifact@v4
        with:
          name: acr_${{ env.ver }}-l_bin.zip
          path: ACR_packaged/out/acr_${{ env.ver }}-l_bin.zip
          compression-level: 0
      - uses: actions/upload-artifact@v4
        with:
          name: acr_${{ env.ver }}-w_bin.zip
          path: ACR_packaged/out/acr_${{ env.ver }}-w_bin.zip
          compression-level: 0

      # Attest build provenance
      - uses: actions/attest-build-provenance@v2
        id: attest-sha256
        with:
          subject-checksums: ACR_packaged/SHA256SUMS
        if: env.is_release == 'true'
      - uses: actions/attest-build-provenance@v2
        id: attest-sha512
        with:
          subject-checksums: ACR_packaged/SHA512SUMS
        if: env.is_release == 'true'

      - name: Create Release
        run: |
          python3 ./repo/source/package_acr_notes.py ./ACR_packaged/SHA256SUMS "$ver" "${{ steps.attest-sha256.outputs.attestation-url }}" "${{ steps.attest-sha512.outputs.attestation-url }}" > release_notes
          cd repo
          gh release create ${{ github.ref_name }} -d -F ../release_notes ../ACR_packaged/{SHA*SUMS,out/*}
        env:
          GH_TOKEN: ${{ github.token }}
        if: env.is_release == 'true'
